spring:
  application:
    name: shianxian-eureka
  #开启权限认证
  security:
    basic:
      enabled: true
    user:
      name: admin
      password: 123456

server:
  host: localhost
  port: 8092

# #
eureka:
  client:
    #此项目不作为客户端注册
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #开启权限验证后Eureka地址为 用户名：密码@地址：端口号，如未开启权限验证则直接使用 地址：端口号
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${server.host}:${server.port}/eureka

# 日志
logging:
  level:
    root: DEBUG
  config: classpath:log/logback-spring-dev.xml