spring:
  application:
    name: shianxian-platform
server:
  port: 8092

# eureka
eurekaServer:
  host: localhost
  port: 8091
  user: admin
  password: 123456

eureka:
  client:
    #将此项目注册到Eureka服务
    register-with-eureka: true
    service-url:
      defaultZone: http://${eurekaServer.user}:${eurekaServer.password}@${eurekaServer.host}:${eurekaServer.port}/eureka

# 日志
logging:
  level:
    root: DEBUG
  config: classpath:log/logback-spring-dev.xml