spring:
  application:
    name: shianxian-platform
server:
  port: 8093

# eureka
eurekaServer:
  host: localhost
  user: admin
  password: 123456
  # eureka端口1
  port1: 8091
  # eureka端口2
  port2: 8092

eureka:
  client:
    #将此项目注册到Eureka服务
    register-with-eureka: true
    service-url:
      defaultZone: http://${eurekaServer.user}:${eurekaServer.password}@${eurekaServer.host}:${eurekaServer.port1}/eureka,http://${eurekaServer.user}:${eurekaServer.password}@${eurekaServer.host}:${eurekaServer.port2}/eureka

# 日志
logging:
  level:
    root: DEBUG
  config: classpath:log/logback-spring-test.xml